Hn bugbash fix
Azure/caf-terraform-landingzones-accelerator pull request #35
Opened 2021-02-18 01:48 UTC by hieumoscow

Added AKS diagnostics settings
Added IP groups

# [Issue-id](https://github.com/Azure/caf-terraform-landingzones-starter/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

## Testing

2021-02-19 06:33 UTC, arnaudlh requested changes

2021-02-19 06:33 UTC, arnaudlh commented on enterprise_scale/construction_sets/aks/module.tf
> +  source = "./public"
Nope :)

2021-02-19 06:55 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/module.tf
> +  source = "./public"
Fixed 👯

2021-03-02 05:36 UTC, arnaudlh approved these changes

2021-03-02 05:37 UTC, merged