Iac and Terratest tests for Secure AKS Construction Set
Azure/caf-terraform-landingzones-accelerator pull request #50
Opened 2021-04-12 18:53 UTC by eedorenko

# Iac and Terratest tests for Secure AKS Construction Set

## Description

- A set of terraform tests for Secure AKS Construction Set
- Iac Pipeline to deploy Secure AKS Construction Set with a Github Actions workflow  
- Iac Pipeline to deploy Secure AKS Construction Set with an Azure Pipeline

## Does this introduce a breaking change

- [ ] YES
- [X ] NO

2021-04-19 16:29 UTC, dtzar commented on .github/workflows/deploy-secure-aks-baseline.yaml
> +name: Deploy_Seccure_Aks_Baseline
Deploy_Seccure_Aks_Baseline --> Deploy_Secure_Aks_Baseline

2021-04-21 14:46 UTC, hieumoscow requested changes
Thank you @eedorenko @sudivate for this great PR, love the content.
Please review some of the comments I have made. I have not fully gone through your PR yet but will resume.
Thanks again guys!

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/flux.tf
> +provider "kubectl" {
I recently deprecate these kubeconfig values due to them being sensitive and us avoiding to store those on tfstate. #52 
Consider to use data source for aks to retrieve these kubeconfig data

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/flux.tf
> +provider "kubectl" {
Flux.tf would fit better in addons folder

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/flux_variables.tf
> +# Flux Variables
Consider to move to addons

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
>  # Define the configuration files to apply, all tfvars files within the above folder recursively
Define the configuration files to apply, all tfvars files within the above folder recursively except for launchpad subfolder which is not relevant for this standalone guide.

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +eval terraform apply ${parameter_files} -var test_prefix=$PREFIX
Is test_prefix a custom var picked up from terratest? Is tag better suited?

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/networking/firewall_application_rule_collection_definition.tfvars
> +          "*.githubusercontent.com",
let's consider if there is a way we can be more restrictive

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/iac-pipeline.md
> +docker run -it --rm -v $(pwd):/tf/caf --user 0  aztfmod/rover:0.14.8-2103.1601 bash
If opened in container in vscode then rover is available in bash. 
The env variables below will be supplied by the rover too after rover login or az login. 
I will help to refine this guide

2021-04-21 14:46 UTC, hieumoscow commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/levels/1_foundation/parameters
> +global_settings.tfvars
Love this approach

2021-04-23 01:09 UTC, merged